### ISSUE TITLE
UTF-8 format

### ISSUE THREAD

**Issue by CKNmusic** [codewithrodi/Lovelace#1]
Hello, how are you? I'm having issues with the accents in the API responses (I believe it's something related to UTF-8 encoding from what I've researched), and instead of the accents, a strange character with a symbol '?' inside a triangle is appearing.

I've already gone through all the code and even tried the help of an AI copilot, but still, I couldn't arrive at any solution :(

P.S.: I also tried changing servers, but it still didn't work.
![imagem_2023-08-29_173131218](https://github.com/codewithrodi/Lovelace/assets/57720235/5d077aa3-b623-44a6-9097-53be5913d47f)

**Comment by rodyherrera** [comment]
Hello "CKNmusic", I was analyzing the problem that you mentioned with the API of the service, I see that the language you are using for the request to Lovelace is "Portuguese". At the time of reading what you are asking me, I assumed that it could be an obvious coding problem, however, I was experimenting through Postman via the web with the same request that you attached to me, and I get the response without coding problems, so it is likely that your computer where you are hosting the service or using Postman is the one with the problem. The service does not present coding problems, according to the tests that I carry out, I will attach the images below.

![Screenshot 2023-08-30 10 45 04 PM](https://github.com/codewithrodi/Lovelace/assets/69746956/60426541-f05f-4265-a293-fcb02c49803f)
![Screenshot 2023-08-30 10 46 55 PM](https://github.com/codewithrodi/Lovelace/assets/69746956/f55f103d-e1bc-41ed-948f-a46a1f6f7101)
![Screenshot 2023-08-30 10 50 40 PM](https://github.com/codewithrodi/Lovelace/assets/69746956/894e558b-2376-4f55-85b3-3f6047ce542e)

If you can experiment from other devices by making a request to the backend hosted locally on your network or using the public API (https://lovelace-backend.codewithrodi.com/api/v1/chat/completions) of the Lovelace DEMO that you can find in the examples of the README.md file or in the documentation (lovelace-docs.codewithrodi.com) you can verify that there is no coding problem. If I'm wrong, and you continue to have the problem on other devices, I'll stay tuned to help you solve the problem you're having with the API.

[Postman WEB](https://www.postman.com/l) 
[Lovelace DOCS](https://lovelace-docs.codewithrodi.com/)
[Lovelace WebAPP](https://lovelace.codewithrodi.com/)

Consider also, that I was testing the request that you are making to the backend from the same web application that Lovelace has (lovelace.codewithrodi.com), I mean, sending the same prompt, and I didn't get coding problems either.

I will be waiting for a possible answer.

A great greeting, from Santiago de Chile.
